In [1]:
import numpy as np
import pandas as pd
import statistics

In [3]:
df = pd.read_csv('boba_nyc.csv')
df.head()

,id,id2,alias,name,image_url,is_closed,url,review_count,categories,rating,...,longitude,geometry,index_right,boro_code,boro_name,county_fip,ntacode,ntaname,shape_area,shape_leng
0,0,Q3fmTHT7zilDWtfzLK9lMA,truedan-new-york-3,Truedan,https://s3-media2.fl.yelpcdn.com/bphoto/BmUZXO...,False,https://www.yelp.com/biz/truedan-new-york-3?ad...,99,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}]",4.5,...,-73.996220,POINT (-73.9962197 40.7191742),94,1.0,Manhattan,61,MN24,SoHo-TriBeCa-Civic Center-Little Italy,2.503268e+07,26855.031527
1,1,7-bx74TooPuZKZDNW4WFcQ,chun-yang-tea-new-york,Chun Yang Tea,https://s3-media1.fl.yelpcdn.com/bphoto/JrGwrZ...,False,https://www.yelp.com/biz/chun-yang-tea-new-yor...,91,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}]",4.5,...,-73.997100,POINT (-73.9971 40.71617),88,1.0,Manhattan,61,MN27,Chinatown,1.450188e+07,20786.254332
2,2,3aypSFXLfkAL4dhHVFobKg,lazy-sundaes-new-york-6,Lazy Sundaes,https://s3-media3.fl.yelpcdn.com/bphoto/kEfCYC...,False,https://www.yelp.com/biz/lazy-sundaes-new-york...,32,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}...",4.5,...,-73.984539,POINT (-73.984539 40.720597),88,1.0,Manhattan,61,MN27,Chinatown,1.450188e+07,20786.254332
3,3,bVJQEeRNi34-3XN_F1AZEg,xing-fu-tang-new-york,Xing Fu Tang,https://s3-media2.fl.yelpcdn.com/bphoto/cyFHFE...,False,https://www.yelp.com/biz/xing-fu-tang-new-york...,91,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}]",4.5,...,-73.987750,POINT (-73.98775 40.7288),139,1.0,Manhattan,61,MN22,East Village,1.089424e+07,13555.232094
4,4,zupVwJAFYkHDwrsQd2ktXA,fiftylan-union-square-new-york-3,FIFTYLAN Union Square,https://s3-media3.fl.yelpcdn.com/bphoto/UIwR20...,False,https://www.yelp.com/biz/fiftylan-union-square...,60,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}]",4.0,...,-73.989191,POINT (-73.989191 40.735516),32,1.0,Manhattan,61,MN21,Gramercy,7.526916e+06,12096.891148

In [4]:
df['categories'][2]

"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}, {'alias': 'desserts', 'title': 'Desserts'}, {'alias': 'shavedice', 'title': 'Shaved Ice'}]"

In [ ]:
# make a col containing a list of category aliases for a given row.
# made by looping through list of dicts(entry in category column),
# gets value of each "alias", appends that to a list.

In [5]:
full_cat_list = []

for i in df.index:

  list_of_dicts = eval(df['categories'][i])
  row_cat_list = []

  for d in list_of_dicts:
    row_cat_list.append(d["alias"])

  full_cat_list.append(row_cat_list)


full_cat_list[2]

['bubbletea', 'desserts', 'shavedice']

In [6]:
df["catlist"] = full_cat_list
df['catlist'][2]

['bubbletea', 'desserts', 'shavedice']

In [7]:
df["catlist"].head()

0                         [bubbletea]
1                         [bubbletea]
2    [bubbletea, desserts, shavedice]
3                         [bubbletea]
4                         [bubbletea]
Name: catlist, dtype: object

In [8]:
df.to_csv('boba_nyc_v2.csv')